networks:
  inception-net:
   name: inception-net
   driver: bridge

volumes:
  maria_db:
   driver: local
   name: maria_db
   driver_opts:
      type: 'none'
      o: bind
      device: ./srcs/data/mysql
  website:
   driver: local
   name: website
   driver_opts:
      type: 'none'
      o: bind
      device: ./srcs/data/wordpress

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - maria_db:/var/lib/mysql
    expose:
        - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty4life
      MYSQL_DATABASE: wp
      MYSQL_USER: hchua
      MYSQL_PASSWORD: qwerty123
    networks:
      - inception-net
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - website:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception-net
    expose:
      - "9000"
    restart: on-failure
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - website:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception-net
    depends_on:
      - wordpress
    restart: on-failure

