FROM debian:buster

RUN apt update && apt install -y nginx openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 \ 
    -keyout /etc/ssl/private/hchua.key \
    -out /etc/ssl/certs/hchua.crt \
    -subj="/C=SG/ST=SG/L=SG/O=1337 School/OU=hchua/CN=hchua.42.fr"

COPY ./conf/default /etc/nginx/sites-available/default

CMD ["nginx", "-g", "daemon off;"]
